name: enterprise
description: "App enterprise"
publish_to: "none"

version: 1.0.0+11

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  flutter_riverpod: ^2.6.1
  go_router: ^14.3.0
  path_provider: ^2.1.5
  dio: ^5.7.0
  flutter_spinkit: ^5.2.1
  get: ^4.6.6
  lottie: ^3.1.3
  fl_chart: ^0.69.2
  syncfusion_flutter_charts: ^27.2.5
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  widgets_easier: ^0.0.10
  flutter_localization: ^0.3.1
  badges: ^3.1.2
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.2
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  loading_animation_widget: ^1.3.0
  http_parser: ^4.0.2
  logger: ^2.5.0
  flutter_svg: ^2.0.16
  url_launcher: ^6.3.1
  shimmer: ^3.0.0
  pull_to_refresh_flutter3: ^2.0.2
  permission_handler: ^11.0.1
  image_cropper: ^9.1.0
  pinput: ^5.0.1
  csv: ^6.0.0
  table_calendar: 3.1.3
  flutter_animate: ^4.5.2
  icons_plus: ^5.0.0
  double_back_to_close_app: ^2.1.0
  mockito: ^5.4.4
  firebase_messaging: ^15.2.4
  firebase_core: ^3.12.1
  flutter_local_notifications: ^18.0.0
  firebase_remote_config: ^5.4.2
  firebase_analytics: ^11.4.4
  firebase_crashlytics: ^4.3.4
  fluttertoast: ^8.2.12
  geocoding: ^3.0.0
  connectivity_plus: ^6.1.3
  sqflite: ^2.4.1
  collection: ^1.18.0
  popover: ^0.3.1
  flutter_launcher_icons: ^0.14.3
  # rive_animated_icon: ^2.0.5
  rive: ^0.13.20
  # camera: ^0.11.1
  flutter_pdfview: ^1.4.0+1
  # syncfusion_flutter_pdfviewer: ^27.2.5
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/svgs/
    - assets/rives/
    - assets/lottie/
    - assets/logo/
  fonts:
    - family: NotoSansLao
      fonts:
        - asset: assets/fonts/NotoSansLao-Bold.ttf
