const Map<String, String> en = {
  "Welcome to NCC": "Welcome to NCC  Group",
  "Enter your phone number": "Enter your phone number and password",
  "Your phone Number": "Phone Number",
  "Password": "Password",
  "phone not found": "Your number is incorrect please check and try again",
  "password wrong": "Your password is incorrect please check and try again",
  "Please enter your password": "Please enter your password",
  "Next": "Login",
  "Cancel": "Cancel",
  "Error": "Sorry",
  "Done": "Done",
  "Slide to Clock In": "Slide to Clock Out",
  "Slide to Clock Out": "Slide to Clock In",
  "Functions": "Functions",
  "Upcoming Events": "Upcoming Events",
  "Team Highlights": "Team Highlights",
  "Click to add your photo or files": "Click to add your photo or files",
  "Sell All": "Sell all",
  "Analytic": 'Analytic',
  "News": 'News',
  "Profile": "Profile",
  "Camera": "Camera",
  "Gallery": "Gallery",
  "Choose Image": "Choose Image",
  "Reason": "Reason",
  "Status": "Status",
  "By": "By",
  "People from your team are on vacation and leave": "People from your team are on vacation and leave",
  "Review": "Review",
  "All Leave History": "All Leave History",
  "You take leavesBy": "You take leavesBy",
  "All Notifications": "All Notifications",
  "Clocked in": "Clocked in",
  "Clocked Out": "Clocked Out",
  "Day off On": "Day off On",
  "Lives In": "Lives In",
  "Department": "Department",
  "Sart Working": "Sart Working",
  // atten
  "You are": "You are",
  "SuccessFully": "Successfully",
  "You": "You 've",
  "NOT": " NOT ",
  "in the clock-in area": "in the clock-in area",
  "Are you sure you want to Clock-in in this location":
      "Are you sure you want to Clock-in in this location?",
  "Have a productive day": "Have a productive day!",
  "Try clocking in earlier tomorrow": "Try clocking in earlier tomorrow 🥰 !",
     "Have a good day": "Have a good day!",
  "Available": "Available",
  "Leave Used": "Leave Used",
  "Image": "Image",
  "Leave Date": "Leave Date",
  "Total Leave": "Total Leave",
  "Approved": "Approved",
  "Rejected": "Rejected",
  "Waiting": "Waiting for approval ",
  "Reject": "Reject",
  "Approv": "Approved",
  "Request details": "Request details",
  //
  "Home": "Home",
  "Attendance overview": "Attendance overview",
  "You were not on time": "You were not on time",
  "Times": "Times",
  "Clock In": "Clock In",
  "Please attach Poto": "Please attach Poto",
  "White cloth field": "| EX: White cloth field",
  "Please enter your current location": "Please enter your current location",
  "In": "In",
  "Out": "Out",
  "Today": "Today",
  "Total Hours": "Total Hours",
  "Attendance history": "Attendance history",
  "days": "days",
  "Annual Leave": "Annual  Leave",
  "Sick Leave": "Sick Leave",
  "Lakit  Leave": "Lakit  Leave",
  "Maternity Leave": 'Maternity Leave',
  "Information": "Information",
  // leave
  "Apply Leave": "Apply Leave",
  "History": 'History',
  "leave type": "Leave Type",
  "Please select a leave type": "--- Please select a leave type ---",
  "Date": "Date",
  "Select Date": "Select Date",
  "Time": "Time",
  "Wear it or not": "Wear it or not",
  "Start time": "Start time",
  "End time": "End time",
  "Please give a reason": "Please give a reason",
  "Please Enter": "Please Enter",
  "References": "References",
  "UploadImage": "UploadImage",
  "Loading": "Loading....",
  "Submit form": "Submit form",
  "Requests": "Requests",
  "Please select a date": "Please select a date",
  //
  "Remaining Leaves": "Remaining Leaves",
  "You take leaves": "You take leaves",
  "Leave history": "Leave history",
  "Announcement": "Announcement",
  "Enter 8-digit phone number": "Enter 8-digit phone number",
  "Please enter the correct password": "Please enter the correct password",
  "Please enter the correct Phone": "Please enter the correct Phone",

  ///fun
  "Applyeave": "Applyeave",
  "Policy": "Policy",
  "Payslips": "Payslips",
  "Calendar": "Calendar",
  "Request OT": "Request OT",
  "From the date": "From the date",
  "To the date": "To the date",

  /// on leave
  "Tomorrow": "Tomorrow",
  "This Week": "This Week",
  "Next Week": "Next Week",
  "After Next Week": "After Next Week",
  "Next Month": "Next Month",

  /// setting
  "System settings": " System settings",
  "Content and display": " Content and display",
  "Language": " Language",
  "Display screen": "Display screen",
  "Login": "Login",
  "Logout": "Logout",
  "Light Mode": "Light Mode",
  "Dark Mode": "Dark Mode",


   // check text input
"Please enter text": "Please enter text",




};
