const Map<String, String> lo = {
  "Welcome to NCC": "ຍິນດີຕ້ອນຮັບສູ່ NCC",
  "Enter your phone number": "ກະລຸນາໃສ່ເບິໂທ ແລະ ລະຫັດຜ່ານເພື່ອເຂົ້າສູ່ລະບົບ",
  "Your phone Number": "ເບີໂທລະສັບຂອງທ່ານ",
  "Password": "ລະຫັດຜ່ານ",
  "Please enter your password": "ກະລຸນາໃສ່ລະຫັດຜ່ານຂອງທ່ານ",
  "Next": "ເຂົ່າສູ່ລະບົບ",
  'Functions': 'ຟັງຊັນ',
  "Home": "ໜ້າຫຼັກ",
  "Analytic": "ລາຍງານ",
  "News": "ຂ່າວສານ",

  "Announcement": "ຂ່າວສານຕ່າງໆ",
  "Profile": "ໂປຣຟາຍ",
  "You Clocked": "",
  "Slide to Clock Out": "ເລື່ອນເພື່ອ ເຂົ້າວຽກ",
  "Slide to Clock In": "ເລື່ອນເພື່ອ ເລີກວຽກ",
  "Team Highlights": "ພະນັກງານລາພັກວັນນີ້",
  "Upcoming Events": "ກິດຈະການທີ່ຈະມາເຖິງ",
  "Sell All": "ທັງໝົດ",
  "Attendance overview": "ພາບລວມການເຂົ້າວຽກ",
  "You were not on time": "ທ່ານມາຊ້າ",
  "Remaining Leaves": "ມື້ລາພັກທີ່ຍັງເຫຼືອ",
  "Leave history": "ປະຫວັດການລາພັກ",
  "Times": "ເວລາ",
  "Date": "ວັນທີ",
  "Days": "ວັນ",
  "In": "ເວລາເຂົ້າ",
  "Out": "ເວລາອອກ",
  "Details": "ລາຍລະອຽດ",
  "Share now": "ແບ່ງປັນດຽວນີ້",
  "ENTERPRISE": "ແອັບ NCC",
  "Policies": "ກົດລະບຽບ",
  "History": "ປະຫັວດ",
  "Apply Leave": "ຂໍລາພັກ",
  "Successfully": "ສົ່ງການຂໍລາພັກສໍາເລັດ!",
  "Your form have submitted and your form will be reviewed soon!":
      "ແບບຟອມຂອງເຈົ້າໄດ້ສົ່ງແລ້ວ ແລະແບບຟອມຂອງເຈົ້າຈະຖືກກວດສອບໃນໄວໆນີ້!",
  "phone not found": "ເບີໂທຂອງທ່ານບໍ່ຖືກຕ້ອງ ກະລຸນາກວດສອບ ແລ້ວລອງອີກຄັ້ງ",
  "password wrong": "ລະຫັດຂອງທ່ານບໍ່ຖືກຕ້ອງ ກະລຸນາກວດສອບ ແລ້ວລອງອີກຄັ້ງ",
  "PhoneIsIncorrect": "ເບີຂອງທ່ານບໍຖືກຕ້ອງ",
  "Done": "ຕົກລົງ",
  "Phone len": "ເບີໂທ ຂອງທ່ານບໍ່ໄດ້ລົງທະບຽນເປັນພະນັກງານໃນບໍລິສັດ",
  "Must start with 20": "ເບີຂອງທ່ານ ຕ້ອງເລີ່ມຕົ້ນດ້ວຍ 20 ຫຼື 30",
  "Enter 8-digit phone number": "ປ້ອນເບີໂທລະສັບ  8 ຕົວເລກ",
  // atten
  "Today": "ວັນນີ້",
  "Total Hours": "ຈໍານວນຊົ່ວໂມງ",
  "Reason": "ເຫດຜົນ",
  "Status": "ສະຖານະ",
  "By": "ໂດຍ",
  "Review": "ທັງໝົດ",

  // leave
  "leave type": "ປະເພດການລາພັກ",
  "Please select a leave type": "--- ກະລຸນາເລືອກປະເພດການລາພັກ ---",
  "Select Date": "ເລືອກວັນທີ",
  "Time": "ເວລາ",
  "Wear it or not": "ໃສ່ ຫລື ບໍ່ໃສ່ກໍ່ໄດ້",
  "Start time": "ເລີ່ມເວລາ",
  "End time": "ສີ້ນສຸດ",
  "Please give a reason": "ກະລຸໃຫ້ເຫດຜົນ",
  "References": "ເອກະສານອ້າງອີງ",
  "Annual Leave": "ລາພັກປະຈໍາປີ",
  "Sick Leave": "ລາປ່ວຍ",
  "Lakit  Leave": "ລາກິດ",
  "Maternity Leave": "ລາເກີດລູກ",

  "Camera": "ກ້ອງຖ່າຍຮູບ",
  "Gallery": "ຄັງຮູບ",
  "Choose Image": "ກະລຸນາເລືອກຮູບພາບ",
  "All Leave History": "ປະຫວັດການລາພັກທັງໝົດ",
  "All Leave": "ການລາພັກທັງໝົດ",
  "You take leavesBy": "ທ່ານລາພັກທັງໝົດ",
  "All Notifications": "ການແຈ້ງເຕືອນທັງໝົດ",
  // fun
  "Applyeave": "ລາພັກ",
  "Policy": "ກົດລະບຽບ",
  "Payslips": "ເງີນເດືອນ",
  "Calendar": "ປະຕິທີນ",
  "Request OT": "ຂໍໂອທີ",
  "Events": "ກິດຈະກໍາ",
  // atten
  "You": "ເຈົ້າ",
//
  "Ok": "ຕົກລົງ",
  "You are": "ເຈົ້າ",
  "NOT": " ບໍ່ໄດ້ ",
  "in the clock-in area": "ຢູ່ໃນພື້ນທີ່ໂມງເຂົ້າວຽກ ຫຼື ອອກວຽກ!",
  "Are you sure you want to Clock-in in this location":
      "ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການ ເຂົ້າວຽກ ຫຼື ອອກວຽກ ໃນສະຖານທີ່ນີ້?",
  "Please enter your current location": "ກະລຸນາໃສ່ສະຖານທີ່ປັດຈຸບັນຂອງທ່ານ",
  "Please attach Poto": "ກະລຸນາແນບຮູບ",
  "White cloth field": "| EX:  ພາກສະໜາມຜ້າຂາວ",
  "Cancel": "ຍົກເລີກ",
  "Clock In": "ບັນທືກ",
  "Attendance history": "ປະຫວັດມາການ",
  "days": "ວັນ",
  "You take leaves": "ເຈົ້າລາພັກ",
  "Number of hours": "ຈໍານວນຊົ່ວໂມງ",
  "ClockIn": "ເວລາເຂົ້າ",
  "ClockOut": "ເວລາອອກ",
  "Have a productive day": "ຂໍໃຫ້ເປັນວັນເຮັດວຽກທີສ້າງສັນ",
  "Have a good day": "ຂໍໃຫ້ເປັນວັນທີດີ",
  "Try clocking in earlier tomorrow": "",

  "SuccessFully": "ສໍາເລັດ!",
  "Clocked in": "ເຂົ້າວຽກ",
  "Clocked Out": "ເລີກວຽກ",
  "People from your team are on vacation and leave":
      "ຄົນຈາກທີມຂອງເຈົ້າກຳລັງພັກຜ່ອນ ແລະອອກເດີນທາງ",

  /// Errror Messages
  "No Internet Connection": "ບໍ່ມີການເຊື່ອມຕໍ່ອິນເຕີເນັດ",
  "Please check your internet connection and try again":
      "ການເຊຶ່ອມຕໍຜຶດພາດ ,ກະລຸນາກວດສອບອິນເຕີເນັດ",
  "Request to API server was cancelled":
      "ການຮ້ອງຂໍຕໍ່ເຄື່ອງແມ່ຂ່າຍ API ໄດ້ຖືກຍົກເລີກ",
  "Connection timeout with API server": "ໝົດເວລາການເຊື່ອມຕໍ່ກັບເຊີບເວີ API",
  "Receive timeout in connection with API server":
      "ໝົດເວລາໃນການເຊື່ອມຕໍ່ກັບເຊີບເວີ API",
  "Connection to server failed, Please check your internet connection":
      "ການເຊື່ອມຕໍ່ກັບເຊີບເວີລົ້ມເຫລວ, ກະລຸນາກວດສອບການເຊື່ອມຕໍ່ອິນເຕີເນັດຂອງທ່ານ",
  "Send timeout in connection with API server":
      "ສົ່ງໝົດເວລາໃນການເຊື່ອມຕໍ່ກັບເຊີບເວີ API",
  "Error": 'ຂໍອະໄພ!',
  "ບໍ່ໄດ້ຮັບອະນຸຍາດ": 'ບໍ່ໄດ້ຮັບອະນຸຍາດ',
  "Internal server error": "ເຊີບເວີພາຍໃນຜິດພາດ",
  "Oops something went wrong": "ຂໍອະໄພ, ມີບາງຢ່າງຜິດພາດເກີດຂຶ້ນ",
  "Edit Profile": "Edit Profile",
  "Please enter Password": "ກະລຸນາປ້ອນລະຫັດຜ່ານ",
  "Please enter PhoneNumber": "ກະລານາປ້ອນເບີໂທ",
  "Error occurred": "ເກີດຂໍ້ຜິດພາດ",

  "Leave Duration": "ໄລຍະເວລາການລາ",
  "Select date": "ເລືອກວັນທີ",
  "Assign temporary work to": "ມອບວຽກຊົ່ວຄາວໃຫ້",
  "Description task list": "ລາຍລະອຽດ / ວຽກງານ",
  "Description": "ກະລຸນາໃສ່ຄໍາອະທິບາຍ",
  "Note Optional": "ຫມາຍເຫດທາງເລືອກ",
  "Submit form": "ສົ່ງແບບຟອມ",
  "Reasons": "ເຫດຜົນ",
  "Please Enter": "ກະລຸນາປ້ອນ",
  "Go to hospital": "ປິ່ນປົວຢູ່ໂຮງຫມໍ",
  "Specific time": "ເວລາທີລາ",
  "SelectTime": "ເລືອກເວລາ",
  "According to": "ອີງຕາມ",
  "Place": "ສະຖານທີ່",
  "Phone": "ເບີໂທ",
  "Solution Treatment": "ການແກ້ໄຂການປິ່ນປົວ",
  "Please enter information": "*ກະລຸນາໃສ່ຂໍ້ມູນ",
  "Request details": "ຮ້ອງຂໍລາຍລະອຽດ ",
  "UploadImage": "ອັບໂຫລດຮູບພາບ",
  "Image": "ຮູບພາບ",
  "Requests": "ຮ້ອງຂໍລາຍລະອຽດ",

  "Loading": "ກໍາລັງສົ່ງ....",
  "Available": "ມື້ລາພັກທີຍັງເຫຼືອ",
  "Leave Used": "ມື້ທີໃຊ້ໄປແລ້ວ",
  "Leave Date": "ລາພັກວັນທີ",
  "Total Leave": "ວັນລາພັກທັງໝົດ",
  "Please enter the correct password": "ກະລຸາປ້ອນລະຫັດຜ່ານໃຫ້ຖືກຕ້ອງ",
  "Please enter the correct Phone": "ກະລຸນາປ້ອນເບີໂທລະສັບໃຫ້ຖືກຕ້ອງ",
  "Approved": "ອະນຸມັດແລ້ວ",
  "Rejected": "ຖືກປະຕິເສດ",
  "Waiting": "ລໍຖ້າອະນຸມັດ",
  "Reject": "ປະຕິເສດ",
  "Approv": "ອະນຸມັດ",

  /// on leave
  "Tomorrow": "ມື້ອື່ນ",
  "This Week": "ອາທິດນີ້",
  "Next Week": "ອາທິດໜ້າ",
  "After Next Week": "ຫຼັງຈາກອາທິດຕໍ່ໄປ",
  "Next Month": "ເດືອນໜ້າ",

  ///
  "Location Permissions Denied": "ການອະນຸຍາດສະຖານທີ່ຖືກປະຕິເສດ",
  "Location permissions are permanently denied. Please enable them in app settings":
      "ການອະນຸຍາດສະຖານທີ່ຖືກປະຕິເສດຢ່າງຖາວອນ. ກະລຸນາເປີດໃຊ້ພວກມັນໃນການຕັ້ງຄ່າແອັບ",

  ///profile
  "Lives In": " ອາໄສຢູ່",
  "Department": " ພະແນກ",
  "Sart Working": " ວັນທີເລີ່ມວຽກ"
};
