const Map<String, String> vi = {
  "Welcome to NCC": "Chào mừng đến với NCC",
  "Enter your phone number": "Nhập số điện thoại của bạn.",
  "Your phone Number": "Số điện thoại của bạn",
  "Please enter your password": "Vui lòng nhập mật khẩu của bạn.",
  "Next": "Đầu gối vào hệ thống",
  "Password": "Mật khẩu",
  'Functions': 'Chức năng',
  "Home": "Trang chủ",
  "Analytic": "Báo cáo",
  "News": "Tin tức",
  "Announcement": "Tin tức",
  "Profile": "Hồ sơ",
  "Upcoming Events": "Sự kiện sắp tới",
  "Slide to Clock Out": "Trượt để kết thúc",
  "Slide to Clock In": "Trượt để vào giờ",
  "Team Highlights": "Điểm nổi bật của đội",
  "Sell All": "Bán tất cả",
  "Attendance overview": "Tổng quan về sự tham dự",
  "You were not on time": "Bạn đã không đúng giờ.",
  "Remaining Leaves": "Lá còn lại",
  "Leave history": "Để lại lịch sử",
  "You take leaves": "Bạn lấy lá.",
  "Date": "Ngày",
  "In": "Ruộng lúa",
  "Out": "Hết giờ",
  "Edit Profile": "Chỉnh sửa hồ sơ",
  "You are": "Bạn là",
  "NOT": "KHÔNG",
  "in the clock-in area": "trong khu vực chấm công",
  "Are you sure you want to Clock-in in this location":
      "Bạn có chắc chắn muốn chấm công ở vị trí này không?",
  "Please enter your current location": "Vui lòng nhập vị trí hiện tại của bạn",
  "Please Enter": "Vui lòng nhập",
  "Please  attach Picture": "Vui lòng đính kèm hình ảnh",
  "UploadImage": "Tải lên hình ảnh",
  "Cancel": "Hủy bỏ",
  "Clock In": "Đồng hồ trong",
  "Policies": "Chính sách",
  "Apply Leave": "Áp dụng nghỉ phép",
  "History": "Lịch sử",
  "Please enter Password": "Vui lòng nhập mật khẩu",
  "Please enter PhoneNumber": "Vui lòng nhập số điện thoại",
  "Error occurred": "Đã xảy ra lỗi",
  "Ok": "Được rồi",
  "Error": "Lỗi",
  "No Internet Connection": "Không có kết nối Internet",
  "Please check your internet connection and try again":
      "Vui lòng kiểm tra kết nối internet của bạn và thử lại",
  "Leave form": "Mẫu đơn xin nghỉ phép",
  "Leave Duration": "Thời gian nghỉ phép",
  "Select date": "Chọn ngày",
  "Assign temporary work to": "Giao công việc tạm thời cho",
  "Description task list": "Mô tả/danh sách nhiệm vụ",
  "Description": "Vui lòng nhập mô tả nghỉ phép",
  "Note Optional": "Lưu ý Tùy chọn",
  "Submit form": "Gửi biểu mẫu",
  "Reasons": "Lý do",
  "Go to hospital": "Đi đến bệnh viện",
  "No": "KHÔNG",
  "Yes": "Đúng",
  "Specific time": "Thời gian cụ thể",
  "SelectTime": "Chọn thời gian",
  "Start time": "Thời gian bắt đầu",
  "According to": "Theo",
  "Place": "Địa điểm",
  "Phone": "Điện thoại",
  "Solution Treatment": "Giải pháp điều trị",
  "Connection timeout with API server": "Hết thời gian kết nối với máy chủ API",
};
