// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCn2pQUo9roY8krOVfuRimudbwUgqzCAo',
    appId: '1:970386284028:web:883b2343a518b2bd106679',
    messagingSenderId: '970386284028',
    projectId: 'enterprise-df25e',
    authDomain: 'enterprise-df25e.firebaseapp.com',
    storageBucket: 'enterprise-df25e.firebasestorage.app',
    measurementId: 'G-S8L298CHB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCwVA7p5UTkSlgfPFGRb2Rb__VvStrlaY',
    appId: '1:970386284028:android:4b1593066e8b20d3106679',
    messagingSenderId: '970386284028',
    projectId: 'enterprise-df25e',
    storageBucket: 'enterprise-df25e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFR1HUFPMiAXrLlLOgRzOnm8xQH-Yrm8Q',
    appId: '1:970386284028:ios:7b8f8c38330edfef106679',
    messagingSenderId: '970386284028',
    projectId: 'enterprise-df25e',
    storageBucket: 'enterprise-df25e.firebasestorage.app',
    iosBundleId: 'com.ncc.enterprise',
  );
}
